package com.example.fivedata;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableWebMvc
@MapperScan("com.example.fivedata.mapper")
public class FivedataApplication {

    public static void main(String[] args) {
        SpringApplication.run(FivedataApplication.class, args);
    }

}
