server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/five-data?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
jwt:
  header: Authorization
  secret: qwertsdfyuiop7418520
